name: Generate Atom Feed

on:
  push:
    branches:
      - main
      - atom-feed #temp during testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true  # checkout submodules

      - name: Set up gemlog.sh
        run: |
          mkdir -p ~/.config/gemlog.sh
          cp .config/gemlog.sh/* ~/.config/gemlog.sh/

      - name: Generate Atom feed and Gemlog Index
        run: |
          ./.modules/gemlog/gemlog.sh ./posts # Run the script

      - name: Debug output
        run: |
          ls -lah ./
          ls -lah ./posts
          ls -lah ./.modules/gemlog

      - name: Commit and push Atom feed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add posts/index.gmi
          git add posts/atom.xml
          git commit -m "Update index.gmi and Atom feed" || echo "No changes to commit"
          git push
